### ISSUE TITLE
Android 6 and better embroidery visualization?

### ISSUE THREAD

**Issue by fabricocouto** [Embroidermodder/MobileViewer#95]
what you need to run on android 6?
can only run on android 9

**Comment by tatarize** [comment]
It should work all the way back to API 16 which is Jellybean. If you mean Marshmallow by Android 6. It should totally do that.

**Comment by fabricocouto** [comment]
I already have a realistic effect embroidery viewer and it was possible to reproduce the effect in C # do you think that with your knowledge it would be possible to study a way to upgrade the mobile to realistic visualization?

**Comment by tatarize** [comment]
There's methods of doing much more realistic effects for the visualizations. Much of what I put in it is garnered from my knowledge of doing Touch Embroidery which does massive amounts of real time editing. Which tends to require a lot more speed so everything is optimized towards animation and rapid displaying. There's also a lot of variability in the 3d display methods between colorizing a textured thread element to doing full 3d rendering with directionality of the light. 

The visualizations could go a few different ways that would be entirely reasonable. The 3d rendering might be overkill but android has OpenGL and Vulcan and the 2d rendering could do things like colorizing a repeating threadlike image. I think this is the method Wilcom uses. 

![wilcomvisual](https://user-images.githubusercontent.com/3302478/67361958-dc93ab80-f51e-11e9-9101-a51eb4f42374.png)

**Comment by tatarize** [comment]
Premier's 3d is still pretty reasonable even without too much flash. It seems like it just mixes some other colors in at places.

![premier3dview](https://user-images.githubusercontent.com/3302478/67362191-5af04d80-f51f-11e9-9dd2-b6d36b8a739a.png)

**Comment by tatarize** [comment]
PE-Explorer does something rather similar. A lot of this seems like it might be done through a couple different means, mostly giving the threads some depth either through varying the color they run through them to give them more than a set of pixels in a line.

![pe-explorer3d](https://user-images.githubusercontent.com/3302478/67362630-4eb8c000-f520-11e9-86a9-ce3a3e0368ce.png)

**Comment by tatarize** [comment]
The android visualization libraries are no slouches. If there's a good way to give a feel of depth then it's likely entirely reasonable to do. My expertise largely comes from getting elements that are the quickest thing to render. And early on in this project I was asked to give it some good legs so if somebody wanted to do some hacking on android they could do that. I had tried a number of methods for doing canvas work for viewing embroidery and to make that stuff reasonably fast. And figured that would give it the best options towards being whatever it would end up being.

I seem to recall that you ported over some other loaders and stuff from libembroidery, and so I hooked that stuff up. I needed some of that same stuff and did some backend work for InkStitch and decided that that well thought through work should be ported back over to Java so I did so in EmbroideryIO (which I need to update).  It ended up being this merely because it's pretty nimble and it's how I got things to work really well with my other embroidery projects. There's not really any reason it can't be anything else. I made sure to upgrade things to use the latest android methods simply to keep it hackable which was my actual marching order there.

**Comment by tatarize** [comment]
Also, #17. Etc.

**Comment by fabricocouto** [comment]
I did something simpler to just improve the visualization in C # and javascrit
![Sem título](https://user-images.githubusercontent.com/20323161/67383247-3a4ae680-f565-11e9-860a-281712e9c68b.png)

**Comment by fabricocouto** [comment]
I was trying to find some way to put this inside the mobile viewer
![65549095_635394980203836_2148195852361924608_o](https://user-images.githubusercontent.com/20323161/67383533-ae858a00-f565-11e9-82ec-070af5123c75.jpg)

**Comment by fabricocouto** [comment]
I thought of using the same reasoning as javascrit using Shader mShader = new LinearGradient (x, y, x, y, new int [] {
                     Color.RED, Color.GREEN, Color.red},
                     null, Shader.TileMode.MIRROR);

**Comment by fabricocouto** [comment]
I thought of something in this reasoning
   static ArrayList <Float> listpoints = new ArrayList ();
I call this list in draw
        int n = listpoints.size ();
       float x1 = 0;
       float y1 = 0;
       for (i = 0; i <n; i ++) {
       float x = listpoints.get (i);
       i = i + 1;
       float y = listpoints.get (i);
       Shader mShader = new LinearGradient (x, y, x1, y1, new int [] {
       Color.RED, Color.GREEN, Color.BLUE},
       null, Shader.TileMode.MIRROR); // CLAMP MIRROR REPEAT
       paint.setShader (mShader);
       canvas.drawLine (x, y, x, y, paint);
       x1 = x;
       y1 = y;
            }
do you think that would be possible

**Comment by tatarize** [comment]
Yes, something almost identical is available within android's canvas routines. 

https://developer.android.com/reference/android/graphics/LinearGradient.html

Though this again will apply to the paint used which is fine this would be very slow unless the entire drawn embroidery  has the same gradient, but then it would look pretty absurd. So really each line needs it's own gradient and realtime speed is out the window.

There's a couple solutions that come to mind. Firstly, have a special slow mode that does the repaints like this which depending on the timings we're dealing with might become unusable, or trivially fine. The alternative is a hybrid mode, where we draw with the current fast routines when we're panning or zooming or what not, but then we redraw the scene in realistic mode if nothing has changed for a second. So it will only render 1 frame after a period of time etc. Then no matter how complex the draw might be it shouldn't really cause any serious issues.

**Comment by tatarize** [comment]
Also:

https://developer.android.com/reference/android/graphics/Shader.TileMode

At a minimum this research must be done. Since this is one of the original features in the list. Your given methodology has all the required parallels within Android and there are methods to mitigate any issues with regard to speed and processing if those prove to be too difficult to perform in realtime.

**Comment by fabricocouto** [comment]
I'm doing some shader tests but I don't have good results with it

            x2Scaled =  ((int)x);
             y2Scaled =   ((int)y);
           
            Shader mShader = new LinearGradient(x2Scaled , y2Scaled, x1Scaled,  y1Scaled, new int[] { 
          Color.GREEN, Color.RED, Color.GREEN
![6f5193e1-019e-4fe0-af95-6770321d1997](https://user-images.githubusercontent.com/20323161/67908802-a9bf6800-fb5b-11e9-8968-b75271a509e2.jpg)
![6f5193e1-019e-4fe0-af95-6770321d1997](https://user-images.githubusercontent.com/20323161/67908809-afb54900-fb5b-11e9-9957-7b0b8c9afa77.jpg)

 },null, Shader.TileMode.CLAMP);
            x1Scaled =  ((int)-x);
            y1Scaled =  ((int)-y);


            paint.setShader(mShader);

**Comment by fabricocouto** [comment]
maybe I'm going the wrong way

**Comment by tatarize** [comment]
@fabricocouto, nah.  The problem is you're using the same Paint for everything. That's actually the fast way. The reason I noted it would be really really slow is that you actually need to do a different Paint for each and every line. Each line needs to be drawn by itself, with a different paint object. Drawn like this the paint effect is for all the stitches. You actually need a different paint for each stitch, which could be dreadfully slow but will actually do the effect.

**Comment by tatarize** [comment]
"Though this again will apply to the paint used which is fine this would be very slow unless the entire drawn embroidery has the same gradient, but then it would look pretty absurd. So really each line needs it's own gradient and realtime speed is out the window." -- 

Here you did the entire drawn embroidery has the same gradient, that looks absurd. You will likely need all lines to have their own gradient, so everything gets a different Paint object. There might be ways to speed that up, but it seems like it's how everything else did it. Each line was painted based on it's own design.

**Comment by fabricocouto** [comment]
I will send you an embroidery visualization code with the effect that is
really very fast and light

Em sex, 1 de nov de 2019 às 08:45, tatarize <notifications@github.com>
escreveu:

**Comment by fabricocouto** [comment]
the look the code
[embroidery realist fill.zip](https://github.com/Embroidermodder/MobileViewer/files/3797776/embroidery.realist.fill.zip)

**Comment by tatarize** [comment]
I must admit that that looks great.  I'll add that method into MobileViewer to at least get things started. It might be slow if it needs constant redraws like when you pan or zoom, but it should at least spit out something that looks kinda threadlike.

**Comment by fabricocouto** [comment]
seriously great if you can and can help me with that my head frying with
the phone

>

**Comment by tatarize** [comment]
![fancyview](https://user-images.githubusercontent.com/3302478/68071652-b5688580-fd39-11e9-9f49-86ecf31ea0a0.png)

Speed isn't terrible, but I did violate a general rule of Android and was creating things inside the routine so I'm going to try something slightly different and more inline with how it's currently setup.

**Comment by fabricocouto** [comment]
really will greatly improve visualization
if you can email me :)

**Comment by tatarize** [comment]
Code is in the Fancyview branch.

https://github.com/Embroidermodder/MobileViewer/tree/tatarize-fancyview

It could also be pushed into main if you generally like it enough. Shouldn't actually be too big of a resource hog though it won't do 200k stitches it will do most reasonable embroideries.

**Comment by tatarize** [comment]
Pull request is at #98 and might actually be worth it to do since the speed doesn't actually seem to be terrible at all. My worries were largely unfounded.

**Comment by fabricocouto** [comment]
I'm very happy to be able to contribute to the growth really was beautiful this code

**Comment by tatarize** [comment]
At some point we could even get @JoshVarga to push a new version. But, yeah, that looks great. If the speed is fine it's likely that we should even do the pull request. My testing device is a 8 year old tablet, which is a bit slowed down with age (they do that).

**Comment by fabricocouto** [comment]
yes yes I think we can find a way to optimize this as very large files like this one from hulk it really get a little slow my phone 6gb memory and 8 nucleus processor

**Comment by tatarize** [comment]
Well, the problem is the paint routine needs to load up a bunch of different paints that all make their own gradients and then fill those gradients in. And does this 1 by 1. It's not quite that this is extremely slow but more generally my other method was hyper-optimized for speed.

As I noted in email: It wouldn't be too hard to switch the shape based on a timer we set. So 1 second after the last draw routine we refresh the screen with the fancier draw routine. It would be a bit slower since we wouldn't have all the data pre-saved like we usually do. And we might be well advised to put it in a try-catch for memory. But, a nice auto-refresh after we're done zooming and panning would be perfectly reasonable.

This routine could perhaps be aborted by a InterruptedThread error. And sort of done in the background so long as it doesn't run out of memory or need to stop because somebody started panning again. Also, if we're doing a once off 1 by 1 segment list we could also perform the out of frame check ourself. We know where the viewport is, so if a line is not within that, we could skip trying to draw that line.

**Comment by fabricocouto** [comment]
I made the drawpath to see if it improved but without success I believe the gradient drawline will not be a good option for android

**Comment by tatarize** [comment]
Well, I wrote up the methodology for how to add in a visualization method. If you have a better option you can do that. That looks great though, it just doesn't go fast. There's an easy fix for that though, use the fast visualization when things are moving and changing and switch to fancy if they are just sitting there for a while.

All the class needs to do to be great is sit there and look pretty, It's pretty easy to switch to the flat-color group paint scheme during pans and zooms.

There are also a couple things to try with regard to memory management. Rather than making each line segment have it's own gradient shader and paint, there's things worth trying to reuse the same paint and just give it a different shader before each draw. And even create the gradient during the paint routine and use the same paint. That way it can be garbage collected on the fly. I'm not sure if gradient objects are memory and process heavy.

But, in any case, I think it's great. It just needs to switch the which method it uses based on the thing it's doing. So we do the fast methods I have in Quick then switch to Fancy if we didn't touch something for a while. So rather than produce 200 heavy frames, it produces 200 light frames and 1 heavy frame.

It just requires a timer that gets reset each time the scene changes. If it manages to count down to zero it sets it to Fancy mode and redraws the scene. Whereas anything else called it in Quick mode. So panning and zooming will be fast, and after a second or so, the visualization will be good.

**Comment by tatarize** [comment]
```

public class EmmPatternFancyView {
    public Paint paint = new Paint();
    EmmPattern pattern;
    ArrayList<FancyLineDraw> drawers = new ArrayList<>();
    float minX = Float.POSITIVE_INFINITY;
    float minY = Float.POSITIVE_INFINITY;
    float maxX = Float.NEGATIVE_INFINITY;
    float maxY = Float.NEGATIVE_INFINITY;

    public EmmPatternFancyView(EmmPattern pattern) {
        this.pattern = pattern;
        FancyLineDraw draw;
        this.paint.setStrokeWidth(3);

        for (EmbObject sb : pattern.asStitchEmbObjects()) {
            EmmThread currentThread = sb.getThread();
            int color = currentThread.getOpaqueColor();
            Points points = sb.getPoints();
            for (int i = 0, ie = points.size()-1; i < ie; i += 1) {
                float x0 = points.getX(i);
                float y0 = points.getY(i);
                float x1 = points.getX(i+1);
                float y1 = points.getY(i+1);
                draw = new FancyLineDraw(x0,y0,x1,y1,color);
                drawers.add(draw);
            }
        }
    }


    public void draw(Canvas canvas) {
        for (FancyLineDraw f : drawers) {
            f.setPaint(this.paint);
            canvas.drawLine(f.x0, f.y0, f.x1, f.y1, this.paint);
        }
    }

    public Bitmap squareThumbnail(int thumbDim) {
        float width = maxX - minX;
        float height = maxY - minY;

        if (width == 0) width = 10;
        if (height == 0) height = 10;
        float scaleX = thumbDim / (width);
        float scaleY = thumbDim / (height);
        float scale = Math.min(scaleY, scaleX);
        float cx = minX + (width / 2);
        float cy = minY + (height / 2);

        Bitmap thumb = Bitmap.createBitmap(thumbDim, thumbDim, Bitmap.Config.ARGB_4444);
        Canvas canvas = new Canvas(thumb);
        canvas.translate(thumb.getWidth() / 2, thumb.getHeight() / 2);
        canvas.scale(scale, scale);
        canvas.translate(-cx, -cy);
        draw(canvas);
        return thumb;
    }

    public boolean isEmpty() {
        return drawers.isEmpty();
    }


    private class FancyLineDraw {
        LinearGradient shader;
        float x0, y0, x1, y1;

        public FancyLineDraw(float x0, float y0, float x1, float y1, int color) {

            this.x0 = x0;
            this.y0 = y0;
            this.x1 = x1;
            this.y1 = y1;
            color = 0xFF000000 | color;
            int dark = adjust(color, -60);
            float[] positions = new float[] { 0, 0.05f, 0.5f, 0.9f, 1.0f };
            int[] colors = new int[] { dark, color, dark, color, dark };
            shader = new LinearGradient(x0, y0, x1, y1, colors, positions, Shader.TileMode.MIRROR);
        }

        public void setPaint(Paint paint) {
            paint.setShader(shader);
        }

        private int adjust(int color, int amount) {
            int a = (color >> 24) & 0xFF;
            int r = (color >> 16) & 0xFF;
            int g = (color >> 8) & 0xFF;
            int b = (color) & 0xFF;
            r = clamp(r + amount);
            g = clamp(g + amount);
            b = clamp(b + amount);
            return a << 24 | r << 16 | g << 8 | b;
        }

        private int clamp(int v) {
            if (v > 255) return 255;
            if (v < 0) return 0;
            return v;
        }
    }
}

```

Here's FancyDraw with a single paint, simply storing the Shader object. It might be massively faster or not  depends on testing.

**Comment by tatarize** [comment]
Here's FancyDraw that creates the LinearGradients on the fly and uses them in the paint.

```
public class EmmPatternFancyView {
    public Paint paint = new Paint();
    EmmPattern pattern;
    ArrayList<FancyLineDraw> drawers = new ArrayList<>();
    float minX = Float.POSITIVE_INFINITY;
    float minY = Float.POSITIVE_INFINITY;
    float maxX = Float.NEGATIVE_INFINITY;
    float maxY = Float.NEGATIVE_INFINITY;

    public EmmPatternFancyView(EmmPattern pattern) {
        this.pattern = pattern;
        FancyLineDraw draw;
        this.paint.setStrokeWidth(3);

        for (EmbObject sb : pattern.asStitchEmbObjects()) {
            EmmThread currentThread = sb.getThread();
            int color = currentThread.getOpaqueColor();
            Points points = sb.getPoints();
            for (int i = 0, ie = points.size()-1; i < ie; i += 1) {
                float x0 = points.getX(i);
                float y0 = points.getY(i);
                float x1 = points.getX(i+1);
                float y1 = points.getY(i+1);
                draw = new FancyLineDraw(x0,y0,x1,y1,color);
                drawers.add(draw);
            }
        }
    }


    public void draw(Canvas canvas) {
        for (FancyLineDraw f : drawers) {
            f.setPaint(this.paint);
            canvas.drawLine(f.x0, f.y0, f.x1, f.y1, this.paint);
        }
    }

    public Bitmap squareThumbnail(int thumbDim) {
        float width = maxX - minX;
        float height = maxY - minY;

        if (width == 0) width = 10;
        if (height == 0) height = 10;
        float scaleX = thumbDim / (width);
        float scaleY = thumbDim / (height);
        float scale = Math.min(scaleY, scaleX);
        float cx = minX + (width / 2);
        float cy = minY + (height / 2);

        Bitmap thumb = Bitmap.createBitmap(thumbDim, thumbDim, Bitmap.Config.ARGB_4444);
        Canvas canvas = new Canvas(thumb);
        canvas.translate(thumb.getWidth() / 2, thumb.getHeight() / 2);
        canvas.scale(scale, scale);
        canvas.translate(-cx, -cy);
        draw(canvas);
        return thumb;
    }

    public boolean isEmpty() {
        return drawers.isEmpty();
    }


    private class FancyLineDraw {
        float x0, y0, x1, y1;
        int color;

        public FancyLineDraw(float x0, float y0, float x1, float y1, int color) {
            this.color = color;
            this.x0 = x0;
            this.y0 = y0;
            this.x1 = x1;
            this.y1 = y1;
        }

        public void setPaint(Paint paint) {
            color = 0xFF000000 | color;
            int dark = adjust(color, -60);
            float[] positions = new float[] { 0, 0.05f, 0.5f, 0.9f, 1.0f };
            int[] colors = new int[] { dark, color, dark, color, dark };
            LinearGradient shader = new LinearGradient(x0, y0, x1, y1, colors, positions, Shader.TileMode.MIRROR);
            paint.setShader(shader);
        }

        private int adjust(int color, int amount) {
            int a = (color >> 24) & 0xFF;
            int r = (color >> 16) & 0xFF;
            int g = (color >> 8) & 0xFF;
            int b = (color) & 0xFF;
            r = clamp(r + amount);
            g = clamp(g + amount);
            b = clamp(b + amount);
            return a << 24 | r << 16 | g << 8 | b;
        }

        private int clamp(int v) {
            if (v > 255) return 255;
            if (v < 0) return 0;
            return v;
        }
    }
}

```

There's every chance that these will make giant differences in time. In fact, I think fancy draw single-paint was great.

**Comment by tatarize** [comment]
@fabricocouto 
I went with the faster FancyView method and added a routine to switch between Fancy and Quick based on whether you are currently in a MotionEvent. The result is really fast movement with fancy visuals when you stop moving.

https://github.com/Embroidermodder/MobileViewer/tree/tatarize-fancyview

Updated on the fancyview branch.

**Comment by fabricocouto** [comment]
O'Que made for one touch was very good.
We could also put in the click of the menus

**Comment by KaiBuskirk** [comment]
did josh push an update?

**Comment by fabricocouto** [comment]
Yes Josh send embroidery pro

**Comment by tatarize** [comment]
I made the pull, but it's not pulled yet. And kinda need Josh to put it up on Google Play. I mean I suppose I could do it but it's better off done from his account. I'm signed off on both the version of MobileViewer in `master` as well as the fancyview update which is notably pretty nice.

I'll likely add something like it to TouchEmbroidery if I go back to updating that code at some point.

**Comment by JoshVarga** [comment]
I'll do the pull soon. I think there was a bit of a hybrid that I worked on. It was pushed to the store as "Embroidery Viewer Pro" https://play.google.com/store/apps/details?id=com.embroidermodder.android&hl=en_US

**Comment by tatarize** [comment]
After pulling be sure to add that link to the readme. It also might be prudent to make a note in the original google play listing.

**Comment by tatarize** [comment]
This was completed Mar 2020.
